### ISSUE TITLE
Difference on ACTIVE vs ENABLED status

### ISSUE THREAD

**Issue by PJEstrada** [ucacoin/Ucacoin-MN#2]
What's the difference between ACTIVE and ENABLED status on the master node? How can I get the node to the ENABLED status?

**Comment by ucacoin** [comment]
Sorry for the late response, but here it is (kind of):
ACTIVE means only that the MN is in the network.
ENABLED means that it is verify and may receive rewards

You get it ENABLED by reserving the correct MN collateral as described in the README.md
